name: Download Bing Wallpaper

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'main'
      
      - name: Create Images Directory
        run: |
          mkdir -p images

      - name: Download Bing Wallpaper
        id: bing
        uses: kelyvin/download-bing-wallpaper-action@v1.0.0

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.0
        with:
          commit_message: 'Update wallpaper image'
          commit_options: "--author='runrab <>'"
          branch: 'main'
          file_pattern: 'images/*'
          file_pattern_exclude: '!.gitignore'
          commit_user_name: 'runrab'
          commit_user_email: ${{ secrets.EMAIL }}
          github_token: ${{ secrets.ACCESS_TOKEN }}

