name: Daily Push

on:
  schedule:
    - cron: '0 0 * * *' # 每天0点推送
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Image
      run: |
        mkdir -p image
        curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299" -L -o image/$(date +"%Y%m%d").jpg https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
        git config --global user.name "${{ secrets.USERNAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        git checkout dev
        git add image/$(date +"%Y%m%d").jpg
        git commit -m "Update image - $(date +"%Y-%m-%d")"
        git push origin dev
        
    - name: Update URL
      run: |
        git checkout main
        echo "https://raw.githubusercontent.com/runrab/bing-img/dev/image/$(date +"%Y%m%d").jpg" >> url.txt
        if [ `cat url.txt | wc -l` -gt 366 ]; then sed -i '1d' url.txt; fi
        git add url.txt
        git commit -m "Update URL - $(date +"%Y-%m-%d")"
        git push

