name: Daily Push

on:
  schedule:
    - cron: '0 0 * * *' # 每天0点推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Image
      run: |
        git checkout dev
        mkdir -p image
        curl -L -o image/$(date +"%Y%m%d").jpg https://source.unsplash.com/1920x1080/?landscape
        git config user.name "${{ github.username }}"
        git config user.email "${{ github.email }}"
        git add image/$(date +"%Y%m%d").jpg
        git commit -m "Update image - $(date +"%Y-%m-%d")"
        git push origin HEAD

    - name: Update URL
      run: |
        git checkout main
        echo "https://raw.githubusercontent.com/${{ github.repo }}/dev/image/$(date +"%Y%m%d").jpg" >> url.txt
        if [ `cat url.txt | wc -l` -gt 366 ]; then sed -i '1d' url.txt; fi
        git add url.txt
        git commit -m "Update URL - $(date +"%Y-%m-%d")"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
